/**
 * @file activity.ts
 * @description Activity logging service for audit trail - tracks user actions
 *              across all entities (assets, subscriptions, projects, etc.)
 * @module lib/core
 */

import { prisma } from './prisma';

export async function logAction(
  tenantId: string,
  actorMemberId: string | null,
  action: string,
  entityType?: string,
  entityId?: string,
  payload?: unknown
) {
  if (!tenantId) {
    console.error('logAction called without tenantId - this is a multi-tenancy violation');
    return null;
  }
  try {
    const activity = await prisma.activityLog.create({
      data: {
        actorMemberId,
        action,
        entityType,
        entityId,
        payload: payload ? JSON.parse(JSON.stringify(payload)) : null,
        tenantId,
      },
    });

    return activity;
  } catch (error) {
    console.error('Failed to log activity:', error);
    // Don't throw - logging should not break the main operation
    return null;
  }
}

// Convenience functions for common actions
export const ActivityActions = {
  ASSET_CREATED: 'ASSET_CREATED',
  ASSET_UPDATED: 'ASSET_UPDATED',
  ASSET_DELETED: 'ASSET_DELETED',
  ASSET_ASSIGNED: 'ASSET_ASSIGNED',
  ASSET_LINKED_PROJECT: 'ASSET_LINKED_PROJECT',

  // Asset Category actions
  ASSET_CATEGORY_CREATED: 'ASSET_CATEGORY_CREATED',
  ASSET_CATEGORY_UPDATED: 'ASSET_CATEGORY_UPDATED',
  ASSET_CATEGORY_DELETED: 'ASSET_CATEGORY_DELETED',

  // Asset Type Mapping actions (custom per-org type-to-category mappings)
  ASSET_TYPE_MAPPING_CREATED: 'ASSET_TYPE_MAPPING_CREATED',
  ASSET_TYPE_MAPPING_UPDATED: 'ASSET_TYPE_MAPPING_UPDATED',
  ASSET_TYPE_MAPPING_DELETED: 'ASSET_TYPE_MAPPING_DELETED',

  // Asset Request Workflow actions
  ASSET_REQUEST_CREATED: 'ASSET_REQUEST_CREATED',
  ASSET_REQUEST_APPROVED: 'ASSET_REQUEST_APPROVED',
  ASSET_REQUEST_REJECTED: 'ASSET_REQUEST_REJECTED',
  ASSET_REQUEST_CANCELLED: 'ASSET_REQUEST_CANCELLED',
  ASSET_ASSIGNMENT_CREATED: 'ASSET_ASSIGNMENT_CREATED',
  ASSET_ASSIGNMENT_ACCEPTED: 'ASSET_ASSIGNMENT_ACCEPTED',
  ASSET_ASSIGNMENT_DECLINED: 'ASSET_ASSIGNMENT_DECLINED',
  ASSET_RETURN_REQUESTED: 'ASSET_RETURN_REQUESTED',
  ASSET_RETURN_APPROVED: 'ASSET_RETURN_APPROVED',
  ASSET_RETURN_REJECTED: 'ASSET_RETURN_REJECTED',

  SUBSCRIPTION_CREATED: 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_UPDATED: 'SUBSCRIPTION_UPDATED',
  SUBSCRIPTION_DELETED: 'SUBSCRIPTION_DELETED',

  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',
  PROJECT_DELETED: 'PROJECT_DELETED',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  PROJECT_STATUS_CHANGED: 'PROJECT_STATUS_CHANGED',

  // Project Budget actions
  PROJECT_BUDGET_CATEGORY_CREATED: 'PROJECT_BUDGET_CATEGORY_CREATED',
  PROJECT_BUDGET_CATEGORY_UPDATED: 'PROJECT_BUDGET_CATEGORY_UPDATED',
  PROJECT_BUDGET_CATEGORY_DELETED: 'PROJECT_BUDGET_CATEGORY_DELETED',

  PROJECT_BUDGET_ITEM_CREATED: 'PROJECT_BUDGET_ITEM_CREATED',
  PROJECT_BUDGET_ITEM_UPDATED: 'PROJECT_BUDGET_ITEM_UPDATED',
  PROJECT_BUDGET_ITEM_DELETED: 'PROJECT_BUDGET_ITEM_DELETED',

  PROJECT_PAYMENT_CREATED: 'PROJECT_PAYMENT_CREATED',
  PROJECT_PAYMENT_UPDATED: 'PROJECT_PAYMENT_UPDATED',
  PROJECT_PAYMENT_DELETED: 'PROJECT_PAYMENT_DELETED',

  PROJECT_REVENUE_CREATED: 'PROJECT_REVENUE_CREATED',
  PROJECT_REVENUE_UPDATED: 'PROJECT_REVENUE_UPDATED',
  PROJECT_REVENUE_DELETED: 'PROJECT_REVENUE_DELETED',

  PROJECT_ASSET_ALLOCATED: 'PROJECT_ASSET_ALLOCATED',
  PROJECT_ASSET_REMOVED: 'PROJECT_ASSET_REMOVED',

  PROJECT_SUBSCRIPTION_ALLOCATED: 'PROJECT_SUBSCRIPTION_ALLOCATED',
  PROJECT_SUBSCRIPTION_REMOVED: 'PROJECT_SUBSCRIPTION_REMOVED',

  ALERT_SUBSCRIPTION_RENEWAL: 'ALERT_SUBSCRIPTION_RENEWAL',
  ALERT_WARRANTY_EXPIRY: 'ALERT_WARRANTY_EXPIRY',
  
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',

  SUPPLIER_CREATED: 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED: 'SUPPLIER_UPDATED',
  SUPPLIER_DELETED: 'SUPPLIER_DELETED',
  SUPPLIER_APPROVED: 'SUPPLIER_APPROVED',
  SUPPLIER_REJECTED: 'SUPPLIER_REJECTED',

  // Task Management actions
  BOARD_CREATED: 'BOARD_CREATED',
  BOARD_UPDATED: 'BOARD_UPDATED',
  BOARD_DELETED: 'BOARD_DELETED',
  BOARD_ARCHIVED: 'BOARD_ARCHIVED',
  BOARD_RESTORED: 'BOARD_RESTORED',
  BOARD_MEMBER_ADDED: 'BOARD_MEMBER_ADDED',
  BOARD_MEMBER_REMOVED: 'BOARD_MEMBER_REMOVED',
  BOARD_MEMBER_UPDATED: 'BOARD_MEMBER_UPDATED',

  COLUMN_CREATED: 'COLUMN_CREATED',
  COLUMN_UPDATED: 'COLUMN_UPDATED',
  COLUMN_DELETED: 'COLUMN_DELETED',
  COLUMN_REORDERED: 'COLUMN_REORDERED',

  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_DELETED: 'TASK_DELETED',
  TASK_MOVED: 'TASK_MOVED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_REOPENED: 'TASK_REOPENED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_UNASSIGNED: 'TASK_UNASSIGNED',

  TASK_LABEL_CREATED: 'TASK_LABEL_CREATED',
  TASK_LABEL_UPDATED: 'TASK_LABEL_UPDATED',
  TASK_LABEL_DELETED: 'TASK_LABEL_DELETED',

  TASK_COMMENT_ADDED: 'TASK_COMMENT_ADDED',
  TASK_COMMENT_UPDATED: 'TASK_COMMENT_UPDATED',
  TASK_COMMENT_DELETED: 'TASK_COMMENT_DELETED',

  TASK_ATTACHMENT_ADDED: 'TASK_ATTACHMENT_ADDED',
  TASK_ATTACHMENT_DELETED: 'TASK_ATTACHMENT_DELETED',

  TASK_CHECKLIST_ITEM_ADDED: 'TASK_CHECKLIST_ITEM_ADDED',
  TASK_CHECKLIST_ITEM_COMPLETED: 'TASK_CHECKLIST_ITEM_COMPLETED',
  TASK_CHECKLIST_ITEM_DELETED: 'TASK_CHECKLIST_ITEM_DELETED',

  // Purchase Request actions
  PURCHASE_REQUEST_CREATED: 'PURCHASE_REQUEST_CREATED',
  PURCHASE_REQUEST_UPDATED: 'PURCHASE_REQUEST_UPDATED',
  PURCHASE_REQUEST_DELETED: 'PURCHASE_REQUEST_DELETED',
  PURCHASE_REQUEST_STATUS_CHANGED: 'PURCHASE_REQUEST_STATUS_CHANGED',
  PURCHASE_REQUEST_APPROVED: 'PURCHASE_REQUEST_APPROVED',
  PURCHASE_REQUEST_REJECTED: 'PURCHASE_REQUEST_REJECTED',
  PURCHASE_REQUEST_COMPLETED: 'PURCHASE_REQUEST_COMPLETED',

  // Leave Management actions
  LEAVE_TYPE_CREATED: 'LEAVE_TYPE_CREATED',
  LEAVE_TYPE_UPDATED: 'LEAVE_TYPE_UPDATED',
  LEAVE_TYPE_DELETED: 'LEAVE_TYPE_DELETED',

  LEAVE_REQUEST_CREATED: 'LEAVE_REQUEST_CREATED',
  LEAVE_REQUEST_UPDATED: 'LEAVE_REQUEST_UPDATED',
  LEAVE_REQUEST_DELETED: 'LEAVE_REQUEST_DELETED',
  LEAVE_REQUEST_APPROVED: 'LEAVE_REQUEST_APPROVED',
  LEAVE_REQUEST_REJECTED: 'LEAVE_REQUEST_REJECTED',
  LEAVE_REQUEST_CANCELLED: 'LEAVE_REQUEST_CANCELLED',

  LEAVE_BALANCE_CREATED: 'LEAVE_BALANCE_CREATED',
  LEAVE_BALANCE_ADJUSTED: 'LEAVE_BALANCE_ADJUSTED',

  // Payroll Management actions
  SALARY_STRUCTURE_CREATED: 'SALARY_STRUCTURE_CREATED',
  SALARY_STRUCTURE_UPDATED: 'SALARY_STRUCTURE_UPDATED',
  SALARY_STRUCTURE_DEACTIVATED: 'SALARY_STRUCTURE_DEACTIVATED',

  PAYROLL_RUN_CREATED: 'PAYROLL_RUN_CREATED',
  PAYROLL_RUN_SUBMITTED: 'PAYROLL_RUN_SUBMITTED',
  PAYROLL_RUN_APPROVED: 'PAYROLL_RUN_APPROVED',
  PAYROLL_RUN_REJECTED: 'PAYROLL_RUN_REJECTED',
  PAYROLL_RUN_PROCESSED: 'PAYROLL_RUN_PROCESSED',
  PAYROLL_RUN_PAID: 'PAYROLL_RUN_PAID',
  PAYROLL_RUN_CANCELLED: 'PAYROLL_RUN_CANCELLED',
  PAYROLL_WPS_GENERATED: 'PAYROLL_WPS_GENERATED',

  PAYSLIP_CREATED: 'PAYSLIP_CREATED',
  PAYSLIP_UPDATED: 'PAYSLIP_UPDATED',

  LOAN_CREATED: 'LOAN_CREATED',
  LOAN_UPDATED: 'LOAN_UPDATED',
  LOAN_APPROVED: 'LOAN_APPROVED',
  LOAN_PAUSED: 'LOAN_PAUSED',
  LOAN_RESUMED: 'LOAN_RESUMED',
  LOAN_COMPLETED: 'LOAN_COMPLETED',
  LOAN_WRITTEN_OFF: 'LOAN_WRITTEN_OFF',
  LOAN_REPAYMENT_RECORDED: 'LOAN_REPAYMENT_RECORDED',

  // Company Document actions
  COMPANY_DOCUMENT_CREATED: 'COMPANY_DOCUMENT_CREATED',
  COMPANY_DOCUMENT_UPDATED: 'COMPANY_DOCUMENT_UPDATED',
  COMPANY_DOCUMENT_DELETED: 'COMPANY_DOCUMENT_DELETED',

  // Approval Policy actions
  APPROVAL_POLICY_CREATED: 'APPROVAL_POLICY_CREATED',
  APPROVAL_POLICY_UPDATED: 'APPROVAL_POLICY_UPDATED',
  APPROVAL_POLICY_DELETED: 'APPROVAL_POLICY_DELETED',

  // Approval Step actions
  APPROVAL_STEP_APPROVED: 'APPROVAL_STEP_APPROVED',
  APPROVAL_STEP_REJECTED: 'APPROVAL_STEP_REJECTED',

  // Delegation actions
  DELEGATION_CREATED: 'DELEGATION_CREATED',
  DELEGATION_UPDATED: 'DELEGATION_UPDATED',
  DELEGATION_DELETED: 'DELEGATION_DELETED',

  // Security audit actions
  SECURITY_IMPERSONATION_STARTED: 'SECURITY_IMPERSONATION_STARTED',
  SECURITY_IMPERSONATION_ENDED: 'SECURITY_IMPERSONATION_ENDED',
  SECURITY_IMPERSONATION_REVOKED: 'SECURITY_IMPERSONATION_REVOKED',
  SECURITY_IMPERSONATION_BLOCKED: 'SECURITY_IMPERSONATION_BLOCKED',

  // Module management actions
  MODULE_INSTALLED: 'MODULE_INSTALLED',
  MODULE_UNINSTALLED: 'MODULE_UNINSTALLED',
} as const;

export type ActivityAction = typeof ActivityActions[keyof typeof ActivityActions];